services:
  streamlit:
    image: ${APP_IMAGE:-mntrading-app}
    command: >
      bash -lc "streamlit run ${APP_PATH:-ui/streamlit_app.py}
      --server.address 0.0.0.0 --server.port 8501"
    environment:
      APP_PATH: ${APP_PATH:-ui/streamlit_app.py}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://mlflow:5000}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL:-http://minio:9000}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-admin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-adminadmin}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      MINIO_BUCKET: ${MINIO_BUCKET:-mlflow}
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    depends_on:
      app:
        condition: service_healthy
      mlflow:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./:/app:rw
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8501/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    profiles: ["ui"]
